runtime: nodejs18
env: standard

automatic_scaling:
  max_instances: 1

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto

beta_settings:
  cloud_sql_instances: travelcompare-412314:asia-east1:travel-compare-db

env_variables:
  NODE_ENV: production
  GCP_PROJECT_ID: travelcompare-412314
  DB_HOST: /cloudsql/travelcompare-412314:asia-east1:travel-compare-db
  DB_DATABASE: travel_compare
  DB_USERNAME: sqlserver
  DB_PASSWORD: travelgogo
  URL: https://travelcompare-412314.de.r.appspot.com