version: '3'
services:
  app:
    user: root
    build: .
    environment:
      - NODE_ENV=production
      - PORT=80
    volumes:
      - /tmp/npm-cache:/tmp/npm-cache
    mem_limit: 550M
    cpus: 0.7

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/travelcompare.store.pem:/etc/ssl/travelcompare.store.pem
      - /etc/ssl/travelcompare.store.key:/etc/ssl/travelcompare.store.key
    depends_on:
      - app
