version: '3'
services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=80

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/travelcompare.store.pem:/etc/ssl/travelcompare.store.pem
      - /etc/ssl/travelcompare.store.key:/etc/ssl/travelcompare.store.key
    restart: on-failure

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: on-failure

volumes:
  jenkins_home:
