version: '4'
services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=80
    ports:
      - "8080:80"
    mem_limit: 950M
    cpus: 0.9

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/travelcompare.store.pem:/etc/ssl/travelcompare.store.pem
      - /etc/ssl/travelcompare.store.key:/etc/ssl/travelcompare.store.key

    depends_on:
      - app
