# version: '3'
# services:
#   app:
#     network_mode: "host"
#     # user: root
#     build: .
#     environment:
#       - NODE_ENV=production
#       - PORT=80
#     # volumes:
#     #   - /tmp/npm-cache:/tmp/npm-cache
#     ports:
#       - "80:80"
#     mem_limit: 550M
#     cpus: 0.7

#   nginx:
#     image: nginx:latest
#     ports:
#       - "443:443"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       - /etc/ssl/travelcompare.store.pem:/etc/ssl/travelcompare.store.pem
#       - /etc/ssl/travelcompare.store.key:/etc/ssl/travelcompare.store.key
#     depends_on:
#       - app
version: '3.8'
services:
  my-jenkins:
    network_mode: "host"
    build: .
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # - /home/ec2-user/.npm:/tmp/npm-cache
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - jenkins_home:/var/jenkins_home
    mem_limit: 600M
    cpus: 0.7

volumes:
  jenkins_home:
