name: Trigger Jenkins on PR Merge

on:
  pull_request_target:
    types: [closed]
    branches: [master]

jobs:
  check-if-merged:
    runs-on: ubuntu-latest
    steps:
      - name: Check if merged
        id: check-merge
        run: |
          isMerged=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
            | jq '.merged')
          echo "isMerged=$isMerged" >> $GITHUB_ENV
      - name: Trigger Jenkins Deployment
        if: env.isMerged == 'true'
        run: |
          curl -X POST ${{ secrets.JENKINS_TRIGGER_URL }}
