name: Trigger Jenkins on PR Merge

on:
  pull_request_target:
    types: [closed]
    branches: [master]

jobs:
  check-if-merged:
    runs-on: ubuntu-latest
    outputs:
      merged: ${{ steps.check-merge.outputs.merged }}
    steps:
      - name: Check if merged
        id: check-merge
        run: |
          isMerged=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
            | jq -r '.merged')
          echo "isMerged=$isMerged"
          echo "merged=$isMerged" >> $GITHUB_ENV
          echo "::set-output name=merged::$isMerged"
      - name: Trigger Jenkins Deployment
        if: ${{ needs.check-if-merged.outputs.merged == 'true' }}
        run: |
          curl -X POST ${{ secrets.JENKINS_TRIGGER_URL }}
